# Generated by Django 5.2.12 on 2026-04-26 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_provider_review_serviceimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
